name: Build docs and extensions and deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "extension_packages/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: figpack-figure/package-lock.json

      - name: Install GUI dependencies and build
        run: |
          cd figpack-figure
          npm ci
          npm run build

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs,test]

      - name: Install build dependencies
        run: |
          pip install build

      - name: Install extension packages
        run: |
          cd extension_packages/figpack_force_graph
          pip install -e .
          cd ../figpack_3d
          npm install
          npm run build
          pip install -e .
          cd ../figpack_spike_sorting
          npm install
          npm run build
          pip install -e .
          cd ../figpack_jfm
          npm install
          npm run build
          pip install -e .
          cd ../figpack_nwb
          npm install
          npm run build
          pip install -e .

      - name: Build documentation
        run: |
          cd docs
          sphinx-build -b html . _build/html
          python devel/generate_basic_views_tutorial_examples.py
          python devel/generate_spike_sorting_tutorial_examples.py
          python devel/generate_extensions_tutorial_examples.py
          python devel/generate_nwb_tutorial_examples.py

      - name: Build extension wheels
        run: ./scripts/build-extension-wheels.sh docs/_build/html/wheels

      - name: Generate wheel index
        run: python scripts/generate-wheel-index.py docs/_build/html/wheels

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
